services:
  app:
    container_name: app
    image: nginx
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - NGINX_PORT=8080

  app-with-expose:
    container_name: app-with-expose
    image: nginx
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - NGINX_PORT=8081
    expose:
      - 8081

  app-with-ports:
    container_name: app-with-ports
    image: nginx
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - NGINX_PORT=8082
    ports:
      - "8082:8082"


