services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    expose:
      - 3306

  adminer:
    image: adminer
    restart: always
    ports:
      - "9001:8080"

